### ISSUE TITLE
Disrespectful repo name

### ISSUE THREAD

**Issue by adrianheine** [albertfdp/did-azer-break-my-stuff#2]
I think the repo name should rather refer to the fact that »my stuff« only worked because of @azer instead of claiming he broke anything which he only could in the first place due to it depending on his work.

**Comment by albertfdp** [comment]
I think you are right, and it was not my intention to be disrespectful at all, so sorry about that. I can change the repo name to something like `did-npm-drama-break-my-stuff`. Is it possible to change a npm module name? Can't really unpublish it, don't want to break other people's stuff ;)

**Comment by jon-bartus** [comment]
I actually disagree with @adrianheine, the name of the repository is factual, not disrespectful. Whether or not your work only worked in the first place because of @azer is immaterial, the fact remains that @azer broke innumerable people's stuff because of something they did. I won't get into a debate here about the motivations for the actions here, that's not relevant either, but the name of the repo is fine, if you really feel the need to give @azer a nod @albertfdp perhaps you might add a note to the description acknowledging the far-reaching benefits of his work.

**Comment by azer** [comment]
I owe you nothing. If your stuff got broken because I don't want to give my work for free to someone's private company, this is between you and NPM. I don't give a fuck about it.

**Comment by jon-bartus** [comment]
@azer who said anything about what you owe? We're discussing the factual matter of whether you took an action that broke an innumerable number of projects or not. You did and admit to it.

Since you've decided to engage I will say the following, though. There's always going to be some sort company involved and open source doesn't absolve you of the need to respect IP laws. You've currently moved from NPM (a company) to GitHub (a company) who will most likely receive the same sort of communications NPM did in the near future from Kik's lawyers. Even if you were to build out a server, get a static IP, and self-host your files you'd be under the same constraints, instead of contacting NPM or Github for their claim Kik would be contacting your ISP (a company), your domain's Registrar (a company), etc.

Whether you choose to see it that way or not, you've changed nothing and caused a great many people a great deal of inconvenience. If you don't wish to feel beholden to people to ensure continued access to your work, that's fine, the solution is simply not to publish it in the first place. When you publish your work for public consumption and then yank the rug out from under everybody on a whim knowing that such an action would break countless projects without warning you shouldn't be surprised when people are upset with you. You didn't owe anybody anything until you chose to offer your work for consumption by others, once you did you owed them, at the very least, the courtesy of not cutting them off without warning.

**Comment by mvaessen** [comment]
I'dd vote for this to be closed.

This will only result in an endless discussion. Damage is done and with this piece of code you can fact-check whether or not Azer's decision did or did not break your application.
